asds

diff --git a/.github/workflows/mail.yml b/.github/workflows/mail.yml
--- a/.github/workflows/mail.yml
+++ b/.github/workflows/mail.yml
@@ -5,12 +5,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Run script
+        continue-on-error: true
         run: |
           echo "This is a test"
-          exit 0 # Simulate failure
+          exit 1 # Simulate failure
   run-always:
     runs-on: ubuntu-latest
-    if: always()
+    if: success()
     needs: fail
     steps:
       - name: Run script
